# This is a Travis CI .yml file for continuous integration.
# Travis allows for software to be built in virtual environments.
# This helps ensure environment and software testing and compatability

language: python

# Build when pushed to any branch
branches:
  only:
  - gh-pages
  - /.*/

# command to install dependencies
install:
  - pip install pygame

matrix:
  include:
  - python: 3.3
    dist: xenial
    sudo: true
    script: python TestSuite.py

  - python: 3.4
    dist: xenial
    sudo: true
    script: python TestSuite.py

  - python: 3.5
    dist: xenial
    sudo: true
    script: python TestSuite.py

  - python: 3.6
    dist: xenial
    sudo: true
    script: python TestSuite.py

  - python: 3.7
    dist: xenial
    sudo: true
    script: python TestSuite.py

  allow_failures:
    - python: 3.3
    - python: 3.4

  fast_finish: true

