from Weapon import *


class WeaponGun(Weapon):
    WEAPON_NAME = "GUN"
    WEAPON_PROJECTILE_SPEED = 10
    WEAPON_COOLDOWN_TIME = 20
    WEAPON_LIFE_TIME = 1000
    WEAPON_PROJECTILE_COLOR = WHITE
    WEAPON_MAX_PROJECTILES = 3
    WEAPON_ANGULAR_SPREAD = 5
    WEAPON_SPRITE_SIZE_X = 2
    WEAPON_SPRITE_SIZE_Y = 2